// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvqueevweckuyeepxfsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cXVlZXZ3ZWNrdXllZXB4ZnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTcwMTEsImV4cCI6MjA2OTUzMzAxMX0.n_3BEGFlLT-hd3X7tfOu0hFpC-ePA5y_7Mlbems7lgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});